-- بنك أميرالد الغرب 💠
-- نفّذ هذا الملف داخل Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.members (
  id uuid primary key default gen_random_uuid(),
  user_id uuid unique not null references auth.users(id) on delete cascade,
  member_id text unique not null,
  display_name text not null,
  role text not null default 'member' check (role in ('member','bank_manager','store_manager','leader')),
  balance bigint not null default 0 check (balance >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  sender_id text,
  receiver_id text,
  amount bigint not null check (amount > 0),
  type text not null default 'transfer',
  created_at timestamptz not null default now()
);

alter table public.members enable row level security;
alter table public.transactions enable row level security;

create policy "members read own profile"
on public.members for select
to authenticated
using (user_id = auth.uid());

create policy "transactions read own"
on public.transactions for select
to authenticated
using (
  sender_id = (select member_id from public.members where user_id = auth.uid())
  or receiver_id = (select member_id from public.members where user_id = auth.uid())
);

-- التحويل يتم داخل معاملة واحدة، ويمنع تعديل الرصيد مباشرة من المتصفح.
create or replace function public.transfer_balance(p_receiver_id text, p_amount bigint)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  sender public.members;
  receiver public.members;
begin
  if p_amount <= 0 then
    raise exception 'المبلغ غير صحيح';
  end if;

  select * into sender from public.members
  where user_id = auth.uid()
  for update;

  if sender.id is null then
    raise exception 'حساب المرسل غير موجود';
  end if;

  select * into receiver from public.members
  where member_id = p_receiver_id
  for update;

  if receiver.id is null then
    raise exception 'المستلم غير موجود';
  end if;

  if sender.member_id = receiver.member_id then
    raise exception 'لا يمكن التحويل لنفس الحساب';
  end if;

  if sender.balance < p_amount then
    raise exception 'الرصيد غير كافٍ';
  end if;

  update public.members set balance = balance - p_amount where id = sender.id;
  update public.members set balance = balance + p_amount where id = receiver.id;

  insert into public.transactions(sender_id, receiver_id, amount, type)
  values(sender.member_id, receiver.member_id, p_amount, 'transfer');

  return json_build_object('success', true);
end;
$$;

revoke all on function public.transfer_balance(text,bigint) from public;
grant execute on function public.transfer_balance(text,bigint) to authenticated;

-- ملاحظة: إنشاء الحسابات يتم من Authentication في Supabase،
-- ثم يضاف سجل العضو في جدول members بواسطة لوحة القائد لاحقًا.
